# Configuration file for WISDM parameter sensitivity analysis

# General run options ----

# Specify the name of the model library
libraryName: wisdm-example

# SyncroSim installation location
# - Leave blank to use default location
ssimLocation: 

# WISDM sensitivity analysis options ----

# Specify the name of the template scenario
templateScenarioName: Brewer's Sparrow

## Random Forest parameter values ----

# Evaluate covariate importance? (boolean - input must be TRUE, FALSE, or both)
evaluateCovariateImportance:
# - Leave blank to use the value in the template scenario
  - TRUE
  - FALSE

# Calculate casewise importance? (boolean - input must be TRUE, FALSE, or both)
calculateCasewiseImportance:
# - Leave blank to use the value in the template scenario
  - TRUE
  - FALSE

# A list of values to test for the number of variables sampled at split 
numberOfVariablesSampledAtSplit:
# - Leave blank to use the value in the template scenario
  - 4
  - 5
  - 6
  
# A list of values to test for the maximum number of nodes
maximumNumberOfNodes:
# - Leave blank to use the value in the template scenario


# A list of values to test for the number of trees
numberOfTrees:
# - Leave blank to use the value in the template scenario
  - 1000
  - 500

# A list of values to test for the node size
nodeSize:
# - Leave blank to use the value in the template scenario
  - 1
  - 2

# A list of values to test for the node size
nodeSize:
# - Leave blank to use the value in the template scenario
  - 1
  - 2

# Normalize votes? (boolean - input must be TRUE, FALSE, or both)
normalizeVotes:
# - Leave blank to use the value in the template scenario
  - TRUE
  - FALSE
  
# Calculate proximity? (boolean - input must be TRUE, FALSE, or both)
calculateProximity:
# - Leave blank to use the value in the template scenario
  - TRUE
  - FALSE
  
# Sample with replacement? (boolean - input must be TRUE, FALSE, or both)
sampleWithReplacement:
# - Leave blank to use the value in the template scenario
  - TRUE
  - FALSE

## Random Forest parameter values ----

# Choose the fitting method
# Leave blank to use the value in the template scenario, or:
# 0 = Use defaults and tuning
# 1 = Use values provided below
fittingMethod: 1

# A list of values to test for the learning rate
learningRate:
# - Leave blank to use the value in the template scenario

# A list of values to test for the number of trees added per stage
numberOfTreesAddedPerStage:
# - Leave blank to use the value in the template scenario

# A list of values to test for the bag fraction
bagFraction:
# - Leave blank to use the value in the template scenario

# A list of values to test for the maximum number of trees
maximumNumberOfTrees:
# - Leave blank to use the value in the template scenario
